name: Luciano Strika (@StrikingLoo)'s Personal Site
permalink: /:title

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

defaults:
  -
    scope:
      path: "wiki/" # an empty string here means all files in the project
    values:
      importance: 5
      is_article: true

    scope:
      path: "_posts/" # an empty string here means all files in the project
    values:
      sitemap: false
      is_article: true
