name: Luciano Strika (@StrikingLoo)'s Personal Site
permalink: /:title

markdown: pandoc
pandoc:
  extensions: [markdown_strict+yaml_metadata_block]
  input: markdown
  output: html5
  filters:
    - add_anchor.lua

defaults:
  -
    scope:
      path: "wiki" # an empty string here means all files in the project
    values:
      importance: 5

    scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      sitemap: false
